### ISSUE TITLE
Character limits make the game too monotonous

### ISSUE THREAD

**Issue by betsythefc** [phikal/ReGeX#23] opened 2016-03-20 22:08 UTC
example:
Match: x yuh
Don't match: tui op
Solution: x|yuh

Because of the character limit, I cannot use some longer, more ingenious solutions, instead I am stuck using "x|yuh" for almost all the solution.

**Comment by phikal** [comment] 2016-03-21 09:34
Interestingly enough you are suggesting the opposite solution that was mentioned in issues like #3 and #4.

One part of the problem is that on lower levels, there aren't many creative solutions (although In your case you could have used `.(.h)?`), and raising the char limit would make the game *too easy*.

On the other hand, I hope this issue will be partially  solved when REDB (Regular Expression Database) from #18 is finally implemented (I am still working on in ._.).

That being said, the maths behind the game also prevents you from leveling up if you use this "cheat" - which in turn either keeps you on the boring levels or even lowers it. Could you tell me on what level you were when you submitted this bug?

**Comment by betsythefc** [comment] 2016-03-21 13:00
Hello Phillip,

I am on level 3.

I also am not the beat at RegEx and am just learning.

Thanks,
Bryce

On March 21, 2016 2:34:40 AM PDT, "Philip K." <notifications@github.com> wrote:
>Interestingly enough you are suggesting the opposite solution that was
>mentioned in issues like #3 and #4.
>
>One part of the problem is that on lower levels, there aren't many
>creative solutions (although In your case you could have used
>`.(.h)?`), and raising the char limit would make the game *too easy*.
>
>On the other hand, I hope this issue will be partially  solved when
>REDB (Regular Expression Database) from #18 is finally implemented (I
>am still working on in ._.).
>
>That being said, the maths behind the game also prevents you from
>leveling up if you use this "cheat" - which in turn either keeps you on
>the boring levels or even lowers it. Could you tell me on what level
>you were when you submitted this bug? 
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/phikal/ReGeX/issues/23#issuecomment-199192541

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by phikal** [comment] 2016-03-21 17:04
It's not really  a fix, but when you get to level 8-9, it gets more interesting~

**Comment by betsythefc** [comment] 2016-03-21 17:18
Okay, I'll try to level up some more and ge there. Thanks!

On March 21, 2016 10:04:33 AM PDT, "Philip K." <notifications@github.com> wrote:
>It's not really  a fix, but when you get to level 8-9, it gets more
>interesting~
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/phikal/ReGeX/issues/23#issuecomment-199382198

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Closed** 2016-09-05 01:27 UTC
