### ISSUE TITLE
No solution displayed

### ISSUE THREAD

**Issue by davidhedlund** [phikal/ReGeX#28] opened 2016-11-07 23:02 UTC
It would be useful to provide a "Solution" button for beginners to learn the game.

**Comment by davidhedlund** [comment] 2016-11-07 23:02
[mylabel:enhancement](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aenhancement%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by phikal** [comment] 2016-11-07 23:22
What should the button do? Should it solve the puzzle, or just display the result?

**Comment by davidhedlund** [comment] 2016-11-07 23:38
@phikal It should show the solution and the result.

**Comment by phikal** [comment] 2016-11-08 07:53
The problem is that currently tasks are either randomly generated, or requested from REDB. 

Ignoring the latter, the problem with finding a solution to random tasks would require something like an artificial intelligence - something I don't think I have the time or skill to implement in a 2MiB Android app (especially since I'm trying to actually reduce the image size).

But I'm not going close the issue just yet, since there was an idea mentioned in #3, to reverse construct tasks from _randomly generated regular expressions_. In this case, it would be petty simple to display the solution(assuming we would have the means to randomly generate a regex).

Side note: when you refer to "beginners [trying] to learn the game", are you talking about people who haven't had any experience with regular expressions in general, or just this game?

**Comment by phikal** [comment] 2016-11-08 17:07
The other possibility, I just thought of, could be to have a few set tasks, with solutions, to serve as a voluntary introduction.

**Comment by davidhedlund** [comment] 2016-11-10 01:17
> The other possibility, I just thought of, could be to have a few set tasks, with solutions, to serve as a voluntary introduction.

You can evaluate this by makign test cases for both solutions too see how easy they are to maintain and how effective they are.

> Side note: when you refer to "beginners [trying] to learn the game", are you talking about people who haven't had any experience with regular expressions in general, or just this game?

I wish that ReGeX could be developed to a smart/fun education app/game to attract people without any experience with regular expression.

I'm so happy to find your software as I strongly believe this is the future of fast learning. In fact, I developed a similar software to learn the multiplication table.

Keep up the good work phikal!

**Comment by davidhedlund** [comment] 2016-11-10 02:08
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by phikal** [comment] 2019-01-17 19:54
2c06e56cf92025bad2b639853d66878c41ae63cd should solve this issue: the [`IntroMatchTask`](https://github.com/phikal/ReGeX/blob/2c06e56cf92025bad2b639853d66878c41ae63cd/app/src/main/java/com/phikal/regex/games/match/IntroMatchTask.java) class contains a few [introductory examples](https://github.com/phikal/ReGeX/blob/2c06e56cf92025bad2b639853d66878c41ae63cd/app/src/main/java/com/phikal/regex/games/match/IntroMatchTask.java#L41) + solutions. The next TODO item will be showing solutions when needed, but that's a different issue. 

If you have any additional examples you'd like me to add, just leave a comment. Other than that I'll be closing this issue.

**Closed by phikal** 2019-01-17 19:54 UTC
