### ISSUE TITLE
User input text loss on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [phikal/ReGeX#36] opened 2016-12-11 22:20 UTC
Text field lose user input on device rotation

Sequence:
1. Click on Settings
2. Click on Set Game Mode
3. Select:
a. Random Word Game
b. REDB Game
4. Enter Text in URL field
5. Orientation Change

**Comment by phikal** [comment] 2016-12-12 12:21
Does this also happen if you don't change the game mode? Because the user input is changed on porous when new game modes are selected, because of the max-char requirements & co.

Other than that, it might have something to do with ee2434173b0293a338b254a0e040849238a934b2.

**Comment by reverse-unina** [comment] 2016-12-12 13:18
This also happens if you don't change the game mode IF the game mode set was random word game OR REDB game

**Comment by phikal** [comment] 2017-07-25 14:12
I'm sorry for the late reply, but I can't reproduce the issue. Could you maybe make screen recording to help reproducing it, if it is actually a bug.

**Comment by phikal** [comment] 2017-08-23 21:42
(Eventually) fixed with 6f5e2834c03e92b45473aee10387fa6e4ade292a

Sorry again for the delay, was too busy, lazy and forgetful and my IDE broke. Will work on #37 tomorrow. Shouldn't take too long.

**Closed by phikal** 2017-08-23 21:42 UTC
